
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

package Languages.Rust;

/** CUP generated class containing symbol constants. */
public class RustParserSym {
  /* terminals */
  public static final int TIMES = 27;
  public static final int MOD = 29;
  public static final int AND = 21;
  public static final int LT = 23;
  public static final int CONTINUE = 11;
  public static final int SEMICOLON = 8;
  public static final int ELSE = 16;
  public static final int PLUS = 25;
  public static final int CASE_OR = 31;
  public static final int OR = 20;
  public static final int EQUAL = 14;
  public static final int WHILE = 19;
  public static final int NOT = 22;
  public static final int FUNCTION = 2;
  public static final int IF = 15;
  public static final int GT = 24;
  public static final int LBRACKET = 6;
  public static final int ID = 33;
  public static final int RBRACKET = 7;
  public static final int NUM = 32;
  public static final int COMMA = 9;
  public static final int EOF = 0;
  public static final int BREAK = 10;
  public static final int DIVIDES = 28;
  public static final int MINUS = 26;
  public static final int ARROW = 30;
  public static final int PRINT = 12;
  public static final int error = 1;
  public static final int LET = 3;
  public static final int EQ = 13;
  public static final int DEFAULT = 18;
  public static final int RPAR = 5;
  public static final int MATCH = 17;
  public static final int LPAR = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FUNCTION",
  "LET",
  "LPAR",
  "RPAR",
  "LBRACKET",
  "RBRACKET",
  "SEMICOLON",
  "COMMA",
  "BREAK",
  "CONTINUE",
  "PRINT",
  "EQ",
  "EQUAL",
  "IF",
  "ELSE",
  "MATCH",
  "DEFAULT",
  "WHILE",
  "OR",
  "AND",
  "NOT",
  "LT",
  "GT",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDES",
  "MOD",
  "ARROW",
  "CASE_OR",
  "NUM",
  "ID"
  };
}

