
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

package Languages.C;

/** CUP generated class containing symbol constants. */
public class CParserSym {
  /* terminals */
  public static final int TIMES = 30;
  public static final int MOD = 32;
  public static final int AND = 24;
  public static final int LT = 26;
  public static final int CONTINUE = 11;
  public static final int ELSE = 17;
  public static final int SEMICOLON = 8;
  public static final int PLUS = 28;
  public static final int OR = 23;
  public static final int INT = 3;
  public static final int EQUAL = 15;
  public static final int WHILE = 22;
  public static final int NOT = 25;
  public static final int SWITCH = 18;
  public static final int IF = 16;
  public static final int GT = 27;
  public static final int COLON = 20;
  public static final int LBRACKET = 6;
  public static final int ID = 34;
  public static final int RBRACKET = 7;
  public static final int NUM = 33;
  public static final int COMMA = 9;
  public static final int EOF = 0;
  public static final int BREAK = 10;
  public static final int DIVIDES = 31;
  public static final int MINUS = 29;
  public static final int CASE = 19;
  public static final int error = 1;
  public static final int EQ = 14;
  public static final int COUT = 12;
  public static final int DEFAULT = 21;
  public static final int RPAR = 5;
  public static final int OUTPUT = 13;
  public static final int VOID = 2;
  public static final int LPAR = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VOID",
  "INT",
  "LPAR",
  "RPAR",
  "LBRACKET",
  "RBRACKET",
  "SEMICOLON",
  "COMMA",
  "BREAK",
  "CONTINUE",
  "COUT",
  "OUTPUT",
  "EQ",
  "EQUAL",
  "IF",
  "ELSE",
  "SWITCH",
  "CASE",
  "COLON",
  "DEFAULT",
  "WHILE",
  "OR",
  "AND",
  "NOT",
  "LT",
  "GT",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDES",
  "MOD",
  "NUM",
  "ID"
  };
}

